[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "shared-py"
version = "0.1.0"
description = "Shared utilities and data for time-traveler"
authors = [{ name = "danidr1" }]
requires-python = ">=3.11"

[tool.setuptools]
packages = ["shared_py"]
include-package-data = true

[tool.setuptools.package-data]
shared_py = ["data/*.json"]
